# Generated by Django 4.0.5 on 2022-06-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant',
            new_name='merchant_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shopper',
            new_name='shopper_id',
        ),
    ]
